name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - run: npm run build:test

      - name: deploy
        uses: JamesIves/github-pages-deploy-action.1.5
        with:
          ACCESS_TOKEN: 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
          BRANCH: master
          FOLDER: dist